/**
 * Infinity Code - Comprehensive Curriculum Configuration
 * 36 major topic categories covering beginner to professional software engineering
 */

export interface CurriculumTopic { name: string; slug: string; description: string; }
export interface CurriculumCategory { id: number; name: string; slug: string; description: string; topics: CurriculumTopic[]; }

export const curriculumCategories: CurriculumCategory[] = [
  {
    id: 1,
    name: "Programming Fundamentals",
    slug: "programming-fundamentals",
    description: "Core concepts every programmer needs to know.",
    topics: [
      { name: "What is programming?", slug: "what-is-programming", description: "Programming is the process of creating instructions that a computer can execute to solve problems or perform tasks." },
      { name: "Algorithms", slug: "algorithms", description: "An algorithm is a step-by-step procedure or set of rules for solving a problem." },
      { name: "Flowcharts", slug: "flowcharts", description: "A flowchart is a visual diagram representing a process or algorithm using shapes and arrows." },
      { name: "Pseudocode", slug: "pseudocode", description: "Pseudocode is a plain-language description of an algorithm without specific syntax." },
      { name: "Variables", slug: "variables", description: "A variable is a named storage location in memory that holds a value which can change during execution." },
      { name: "Constants", slug: "constants", description: "A constant is a value that cannot be changed after it is assigned." },
      { name: "Data types", slug: "data-types", description: "A data type defines the kind of value a variable can hold, such as numbers, text, or booleans." },
      { name: "Operators", slug: "operators", description: "Operators are symbols that perform operations on values like arithmetic, comparison, and logical operations." },
      { name: "Expressions", slug: "expressions", description: "An expression is a combination of values, variables, and operators that evaluates to a result." },
      { name: "Input and output", slug: "input-and-output", description: "Input is data received by a program; output is data produced by the program." },
      { name: "Type conversion", slug: "type-conversion", description: "Type conversion changes a value from one data type to another." },
      { name: "Conditional statements", slug: "conditional-statements", description: "Conditional statements allow a program to make decisions based on conditions." },
      { name: "if, else, else if", slug: "if-else-else-if", description: "These execute different blocks of code depending on whether conditions are true or false." },
      { name: "switch", slug: "switch", description: "A switch statement evaluates an expression and executes code for the matching case." },
      { name: "Loops", slug: "loops", description: "Loops repeat a block of code multiple times until a condition is met." },
      { name: "for", slug: "for", description: "A for loop repeats code a specific number of times with a counter." },
      { name: "while", slug: "while", description: "A while loop repeats code as long as a condition remains true." },
      { name: "do while", slug: "do-while", description: "A do-while loop executes at least once, then repeats while a condition is true." },
      { name: "Functions", slug: "functions", description: "A function is a reusable block of code that performs a specific task." },
      { name: "Parameters", slug: "parameters", description: "Parameters are variables in a function signature that receive values when called." },
      { name: "Return values", slug: "return-values", description: "A return value is the result a function sends back to the caller." },
      { name: "Scope", slug: "scope", description: "Scope determines the visibility and accessibility of variables in a program." },
      { name: "Recursion", slug: "recursion", description: "Recursion is a technique where a function calls itself to solve a problem." },
      { name: "Error handling", slug: "error-handling", description: "Error handling is the process of managing errors during program execution." },
      { name: "Debugging", slug: "debugging", description: "Debugging is the process of finding and fixing errors in code." },
      { name: "Comments", slug: "comments", description: "Comments are notes in code ignored by the compiler, explaining the code." },
      { name: "Code style", slug: "code-style", description: "Code style refers to conventions for formatting and organising code." },
      { name: "Naming conventions", slug: "naming-conventions", description: "Naming conventions are rules for naming variables and functions consistently." },
    ],
  },
  {
    id: 2,
    name: "Data Structures",
    slug: "data-structures",
    description: "Ways to organise, store, and manage data efficiently.",
    topics: [
      { name: "Arrays", slug: "arrays", description: "An array stores multiple values in a contiguous block of memory, accessed by index." },
      { name: "Strings", slug: "strings", description: "A string is a sequence of characters used to represent text." },
      { name: "Objects", slug: "objects", description: "An object stores data as key-value pairs." },
      { name: "Sets", slug: "sets", description: "A set is a collection of unique values." },
      { name: "Maps", slug: "maps", description: "A map stores key-value pairs with fast lookups." },
      { name: "Stacks", slug: "stacks", description: "A stack follows Last-In-First-Out (LIFO) principle." },
      { name: "Queues", slug: "queues", description: "A queue follows First-In-First-Out (FIFO) principle." },
      { name: "Linked lists", slug: "linked-lists", description: "A linked list links elements (nodes) using pointers." },
      { name: "Hash tables", slug: "hash-tables", description: "A hash table maps keys to values using a hash function." },
      { name: "Trees", slug: "trees", description: "A tree is a hierarchical data structure with a root and no cycles." },
      { name: "Binary trees", slug: "binary-trees", description: "A binary tree where each node has at most two children." },
      { name: "Binary search trees", slug: "binary-search-trees", description: "A BST where left child is smaller and right is larger than parent." },
      { name: "Heaps", slug: "heaps", description: "A heap satisfies the heap property." },
      { name: "Graphs", slug: "graphs", description: "A graph has vertices connected by edges." },
      { name: "Tries", slug: "tries", description: "A trie stores strings for efficient prefix searches." },
      { name: "Priority queues", slug: "priority-queues", description: "A priority queue removes elements by priority order." },
    ],
  },
  {
    id: 3,
    name: "Algorithms",
    slug: "algorithms",
    description: "Step-by-step procedures for solving problems efficiently.",
    topics: [
      { name: "Searching", slug: "searching", description: "Searching algorithms find an element in a data structure." },
      { name: "Linear search", slug: "linear-search", description: "Checks each element one by one. O(n)." },
      { name: "Binary search", slug: "binary-search", description: "Divides search interval in half. O(log n)." },
      { name: "Sorting", slug: "sorting", description: "Arranges elements in order." },
      { name: "Bubble sort", slug: "bubble-sort", description: "Swaps adjacent elements. O(n^2)." },
      { name: "Selection sort", slug: "selection-sort", description: "Finds minimum and places at beginning. O(n^2)." },
      { name: "Insertion sort", slug: "insertion-sort", description: "Inserts each element into position. O(n^2)." },
      { name: "Merge sort", slug: "merge-sort", description: "Divides, sorts, merges. O(n log n)." },
      { name: "Quick sort", slug: "quick-sort", description: "Partitions around pivot. O(n log n) average." },
      { name: "Recursion", slug: "recursion", description: "Solves by solving smaller instances of same problem." },
      { name: "Divide and conquer", slug: "divide-and-conquer", description: "Breaks problem into sub-problems, combines results." },
      { name: "Greedy algorithms", slug: "greedy-algorithms", description: "Makes locally optimal choice at each step." },
      { name: "Dynamic programming", slug: "dynamic-programming", description: "Stores sub-problem results to avoid recomputation." },
      { name: "Backtracking", slug: "backtracking", description: "Tries options, abandons non-solution paths." },
      { name: "Graph traversal", slug: "graph-traversal", description: "Visits all vertices in specific order." },
      { name: "Breadth-first search", slug: "breadth-first-search", description: "Explores level by level using a queue." },
      { name: "Depth-first search", slug: "depth-first-search", description: "Goes deep before backtracking." },
      { name: "Shortest-path algorithms", slug: "shortest-path-algorithms", description: "Finds lowest-cost path, e.g., Dijkstra." },
      { name: "Big O notation", slug: "big-o-notation", description: "Describes upper bound of complexity." },
      { name: "Time complexity", slug: "time-complexity", description: "How runtime grows with input size." },
      { name: "Space complexity", slug: "space-complexity", description: "Memory usage relative to input size." },
    ],
  },
  {
    id: 4,
    name: "HTML",
    slug: "html",
    description: "The standard markup language for creating web pages.",
    topics: [
      { name: "HTML fundamentals", slug: "html-fundamentals", description: "HTML is the standard markup language for web page structure." },
      { name: "Document structure", slug: "document-structure", description: "An HTML document has DOCTYPE, html, head, and body elements." },
      { name: "Headings", slug: "headings", description: "HTML headings h1 to h6 define title hierarchy." },
      { name: "Paragraphs", slug: "paragraphs", description: "The p element defines a paragraph of text." },
      { name: "Links", slug: "links", description: "The a element creates hyperlinks using href." },
      { name: "Images", slug: "images", description: "The img element displays images using src and alt." },
      { name: "Lists", slug: "lists", description: "HTML lists include ordered, unordered, and definition lists." },
      { name: "Tables", slug: "tables", description: "HTML tables display tabular data using table, tr, th, td." },
      { name: "Forms", slug: "forms", description: "HTML forms collect user input with various controls." },
      { name: "Inputs", slug: "inputs", description: "Input elements create text, email, password, and file inputs." },
      { name: "Buttons", slug: "buttons", description: "The button element creates clickable buttons." },
      { name: "Semantic HTML", slug: "semantic-html", description: "Semantic HTML uses header, nav, main, article, footer for meaning." },
      { name: "Audio", slug: "audio", description: "The audio element embeds sound content." },
      { name: "Video", slug: "video", description: "The video element embeds video content." },
      { name: "Iframes", slug: "iframes", description: "An iframe embeds another HTML document." },
      { name: "Metadata", slug: "metadata", description: "HTML metadata provides page info like title and charset." },
      { name: "Accessibility", slug: "accessibility", description: "HTML accessibility ensures content is usable by people with disabilities." },
      { name: "SEO fundamentals", slug: "seo-fundamentals", description: "SEO involves structuring HTML for search engines." },
    ],
  },
  {
    id: 5,
    name: "CSS",
    slug: "css",
    description: "The style sheet language for describing web page presentation.",
    topics: [
      { name: "CSS fundamentals", slug: "css-fundamentals", description: "CSS controls visual presentation of HTML elements." },
      { name: "Selectors", slug: "selectors", description: "CSS selectors target elements using element, class, and ID." },
      { name: "Properties", slug: "properties", description: "CSS properties define style aspects like color and margin." },
      { name: "Values", slug: "values", description: "CSS values are assigned to properties." },
      { name: "Box model", slug: "box-model", description: "The box model describes content, padding, border, and margin." },
      { name: "Margin", slug: "margin", description: "Margin is space outside an element border." },
      { name: "Padding", slug: "padding", description: "Padding is space between content and border." },
      { name: "Borders", slug: "borders", description: "CSS borders are lines around an element." },
      { name: "Colours", slug: "colours", description: "CSS colours use named colours, hex, RGB, or HSL." },
      { name: "Typography", slug: "typography", description: "CSS typography controls text appearance." },
      { name: "Fonts", slug: "fonts", description: "CSS fonts define typefaces." },
      { name: "Positioning", slug: "positioning", description: "CSS positioning controls element placement." },
      { name: "Flexbox", slug: "flexbox", description: "Flexbox arranges elements in rows or columns." },
      { name: "CSS Grid", slug: "css-grid", description: "CSS Grid creates two-dimensional layouts." },
      { name: "Responsive design", slug: "responsive-design", description: "Responsive design ensures pages work on all devices." },
      { name: "Media queries", slug: "media-queries", description: "Media queries apply CSS based on device characteristics." },
      { name: "Animations", slug: "animations", description: "CSS animations create transitions using keyframes." },
      { name: "Transitions", slug: "transitions", description: "CSS transitions interpolate between property values." },
      { name: "Transforms", slug: "transforms", description: "CSS transforms modify element appearance." },
      { name: "Pseudo-classes", slug: "pseudo-classes", description: "Pseudo-classes target elements in specific states." },
      { name: "Pseudo-elements", slug: "pseudo-elements", description: "Pseudo-elements target parts of elements." },
      { name: "CSS variables", slug: "css-variables", description: "CSS variables store reusable values." },
      { name: "Dark mode", slug: "dark-mode", description: "Dark mode displays light text on dark backgrounds." },
      { name: "Modern CSS", slug: "modern-css", description: "Modern CSS includes container queries and nesting." },
    ],
  },
  {
    id: 6,
    name: "JavaScript",
    slug: "javascript",
    description: "The programming language of the web.",
    topics: [
      { name: "JavaScript fundamentals", slug: "javascript-fundamentals", description: "JavaScript enables interactive web pages." },
      { name: "Variables", slug: "variables", description: "JS variables store data using var, let, const." },
      { name: "Data types", slug: "data-types", description: "JS types include string, number, boolean, object, array." },
      { name: "Operators", slug: "operators", description: "JS operators include arithmetic, comparison, logical." },
      { name: "Functions", slug: "functions", description: "JS functions are reusable code blocks." },
      { name: "Arrow functions", slug: "arrow-functions", description: "Arrow functions provide concise syntax." },
      { name: "Arrays", slug: "arrays", description: "JS arrays are ordered collections with map, filter, reduce." },
      { name: "Objects", slug: "objects", description: "JS objects are key-value pair collections." },
      { name: "Destructuring", slug: "destructuring", description: "Destructuring unpacks values from arrays and objects." },
      { name: "Spread/rest operators", slug: "spread-rest-operators", description: "Spread expands iterables; rest collects elements." },
      { name: "Template literals", slug: "template-literals", description: "Template literals use backticks for string interpolation." },
      { name: "Scope", slug: "scope", description: "Scope determines variable accessibility." },
      { name: "Closures", slug: "closures", description: "A closure retains access to outer scope variables." },
      { name: "Callbacks", slug: "callbacks", description: "A callback is a function passed as an argument." },
      { name: "Higher-order functions", slug: "higher-order-functions", description: "Functions that accept or return functions." },
      { name: "Array methods", slug: "array-methods", description: "Methods like map, filter, reduce, forEach." },
      { name: "DOM manipulation", slug: "dom-manipulation", description: "Changing HTML elements using JavaScript." },
      { name: "Events", slug: "events", description: "JS events are actions handled by event listeners." },
      { name: "Local storage", slug: "local-storage", description: "Stores key-value pairs persistently in browser." },
      { name: "Session storage", slug: "session-storage", description: "Stores data for a page session." },
      { name: "JSON", slug: "json", description: "Lightweight data interchange format." },
      { name: "Fetch API", slug: "fetch-api", description: "Modern interface for HTTP requests." },
      { name: "Promises", slug: "promises", description: "Represents eventual completion of async operations." },
      { name: "Async/await", slug: "async-await", description: "Makes async code look synchronous." },
      { name: "Error handling", slug: "error-handling", description: "Uses try-catch-finally for runtime errors." },
      { name: "Modules", slug: "modules", description: "Import/export for reusable code files." },
      { name: "ES6+", slug: "es6", description: "Modern JS features since ECMAScript 2015." },
      { name: "Regular expressions", slug: "regular-expressions", description: "Patterns for matching and replacing text." },
      { name: "Web APIs", slug: "web-apis", description: "Browser interfaces like DOM, Fetch, Canvas." },
    ],
  },
  {
    id: 7,
    name: "TypeScript",
    slug: "typescript",
    description: "A typed superset of JavaScript with static type checking.",
    topics: [
      { name: "TypeScript fundamentals", slug: "typescript-fundamentals", description: "TypeScript adds static types to JavaScript." },
      { name: "Type annotations", slug: "type-annotations", description: "Explicitly specify types for variables and parameters." },
      { name: "Primitive types", slug: "primitive-types", description: "string, number, boolean, null, undefined, symbol." },
      { name: "Arrays", slug: "arrays", description: "Typed collections declared as type[]." },
      { name: "Tuples", slug: "tuples", description: "Fixed-length arrays with known types per index." },
      { name: "Enums", slug: "enums", description: "Named constants for better readability." },
      { name: "Interfaces", slug: "interfaces", description: "Define the shape of objects." },
      { name: "Type aliases", slug: "type-aliases", description: "Custom names for any type." },
      { name: "Union types", slug: "union-types", description: "Value can be one of several types." },
      { name: "Intersection types", slug: "intersection-types", description: "Combine multiple types into one." },
      { name: "Literal types", slug: "literal-types", description: "Restrict to a specific value." },
      { name: "Generics", slug: "generics", description: "Reusable components with type parameters." },
      { name: "Optional properties", slug: "optional-properties", description: "Marked with ? allowing absence." },
      { name: "Type narrowing", slug: "type-narrowing", description: "Refine union type to specific type." },
      { name: "Type guards", slug: "type-guards", description: "Runtime checks that narrow types." },
      { name: "Utility types", slug: "utility-types", description: "Partial, Pick, Omit, Record, Readonly." },
      { name: "Classes", slug: "classes", description: "Typed properties with access modifiers." },
      { name: "Access modifiers", slug: "access-modifiers", description: "public, private, protected." },
      { name: "Abstract classes", slug: "abstract-classes", description: "Base classes that cannot be instantiated." },
      { name: "Type declarations", slug: "type-declarations", description: ".d.ts files provide types for JS libraries." },
      { name: "tsconfig", slug: "tsconfig", description: "Configures the TypeScript compiler." },
      { name: "TypeScript with React", slug: "typescript-with-react", description: "Type safety for components, props, state." },
      { name: "Advanced TypeScript", slug: "advanced-typescript", description: "Conditional types, mapped types, template literal types." },
    ],
  },
  {
    id: 8,
    name: "React",
    slug: "react",
    description: "A JavaScript library for building user interfaces.",
    topics: [
      { name: "React fundamentals", slug: "react-fundamentals", description: "React builds UIs using components and virtual DOM." },
      { name: "Components", slug: "components", description: "Reusable UI pieces accepting props." },
      { name: "JSX", slug: "jsx", description: "Syntax extension looking like HTML." },
      { name: "Props", slug: "props", description: "Inputs passed from parent to child." },
      { name: "State", slug: "state", description: "Internal data triggering re-renders." },
      { name: "Events", slug: "events", description: "Synthetic events via onClick, onChange." },
      { name: "Conditional rendering", slug: "conditional-rendering", description: "Display different UI based on conditions." },
      { name: "Lists", slug: "lists", description: "Render arrays using map with keys." },
      { name: "Forms", slug: "forms", description: "Controlled components managed by state." },
      { name: "Hooks", slug: "hooks", description: "Use state and features in functional components." },
      { name: "useState", slug: "usestate", description: "Adds local state to components." },
      { name: "useEffect", slug: "useeffect", description: "Manages side effects." },
      { name: "useContext", slug: "usecontext", description: "Reads Context avoiding prop drilling." },
      { name: "useRef", slug: "useref", description: "Mutable reference for DOM access." },
      { name: "Custom hooks", slug: "custom-hooks", description: "Reusable logic extraction." },
      { name: "React Router", slug: "react-router", description: "Client-side navigation." },
      { name: "Authentication", slug: "authentication", description: "User sessions and protected routes." },
      { name: "API integration", slug: "api-integration", description: "HTTP requests with fetch or axios." },
      { name: "State management", slug: "state-management", description: "Context API, Redux, Zustand." },
      { name: "Performance", slug: "performance", description: "memo, useMemo, useCallback." },
      { name: "Lazy loading", slug: "lazy-loading", description: "React.lazy and Suspense." },
      { name: "Error boundaries", slug: "error-boundaries", description: "Catch errors in child components." },
      { name: "React with TypeScript", slug: "react-with-typescript", description: "Type safety for props, state, hooks." },
      { name: "React project structure", slug: "react-project-structure", description: "Organising files by feature or type." },
    ],
  },
  {
    id: 9,
    name: "Frontend Development",
    slug: "frontend-development",
    description: "Building responsive, accessible web interfaces.",
    topics: [
      { name: "Responsive design", slug: "responsive-design", description: "Responsive design - Learn more about Responsive design." },
      { name: "UI development", slug: "ui-development", description: "UI development - Learn more about UI development." },
      { name: "UX fundamentals", slug: "ux-fundamentals", description: "UX fundamentals - Learn more about UX fundamentals." },
      { name: "Accessibility", slug: "accessibility", description: "Accessibility - Learn more about Accessibility." },
      { name: "Component design", slug: "component-design", description: "Component design - Learn more about Component design." },
      { name: "Design systems", slug: "design-systems", description: "Design systems - Learn more about Design systems." },
      { name: "Forms", slug: "forms", description: "Forms - Learn more about Forms." },
      { name: "Validation", slug: "validation", description: "Validation - Learn more about Validation." },
      { name: "API integration", slug: "api-integration", description: "API integration - Learn more about API integration." },
      { name: "Authentication", slug: "authentication", description: "Authentication - Learn more about Authentication." },
      { name: "State management", slug: "state-management", description: "State management - Learn more about State management." },
      { name: "Browser storage", slug: "browser-storage", description: "Browser storage - Learn more about Browser storage." },
      { name: "Performance", slug: "performance", description: "Performance - Learn more about Performance." },
      { name: "Web security", slug: "web-security", description: "Web security - Learn more about Web security." },
      { name: "Testing", slug: "testing", description: "Testing - Learn more about Testing." },
      { name: "Deployment", slug: "deployment", description: "Deployment - Learn more about Deployment." },
    ],
  },
  {
    id: 10,
    name: "Backend Development",
    slug: "backend-development",
    description: "Server-side development with Node.js and Express.",
    topics: [
      { name: "Backend fundamentals", slug: "backend-fundamentals", description: "Backend fundamentals - Learn more about Backend fundamentals." },
      { name: "Node.js", slug: "node-js", description: "Node.js - Learn more about Node.js." },
      { name: "Express", slug: "express", description: "Express - Learn more about Express." },
      { name: "REST APIs", slug: "rest-apis", description: "REST APIs - Learn more about REST APIs." },
      { name: "HTTP methods", slug: "http-methods", description: "HTTP methods - Learn more about HTTP methods." },
      { name: "Status codes", slug: "status-codes", description: "Status codes - Learn more about Status codes." },
      { name: "Middleware", slug: "middleware", description: "Middleware - Learn more about Middleware." },
      { name: "Routing", slug: "routing", description: "Routing - Learn more about Routing." },
      { name: "Controllers", slug: "controllers", description: "Controllers - Learn more about Controllers." },
      { name: "Services", slug: "services", description: "Services - Learn more about Services." },
      { name: "Authentication", slug: "authentication", description: "Authentication - Learn more about Authentication." },
      { name: "Authorisation", slug: "authorisation", description: "Authorisation - Learn more about Authorisation." },
      { name: "JWT", slug: "jwt", description: "JWT - Learn more about JWT." },
      { name: "Sessions", slug: "sessions", description: "Sessions - Learn more about Sessions." },
      { name: "Error handling", slug: "error-handling", description: "Error handling - Learn more about Error handling." },
      { name: "File uploads", slug: "file-uploads", description: "File uploads - Learn more about File uploads." },
      { name: "Logging", slug: "logging", description: "Logging - Learn more about Logging." },
      { name: "Security", slug: "security", description: "Security - Learn more about Security." },
      { name: "API testing", slug: "api-testing", description: "API testing - Learn more about API testing." },
    ],
  },
  {
    id: 11,
    name: "Databases",
    slug: "databases",
    description: "Relational and NoSQL database management.",
    topics: [
      { name: "Database fundamentals", slug: "database-fundamentals", description: "Database fundamentals - Learn more about Database fundamentals." },
      { name: "Relational databases", slug: "relational-databases", description: "Relational databases - Learn more about Relational databases." },
      { name: "SQL", slug: "sql", description: "SQL - Learn more about SQL." },
      { name: "Tables", slug: "tables", description: "Tables - Learn more about Tables." },
      { name: "Primary keys", slug: "primary-keys", description: "Primary keys - Learn more about Primary keys." },
      { name: "Foreign keys", slug: "foreign-keys", description: "Foreign keys - Learn more about Foreign keys." },
      { name: "Relationships", slug: "relationships", description: "Relationships - Learn more about Relationships." },
      { name: "CRUD", slug: "crud", description: "CRUD - Learn more about CRUD." },
      { name: "SELECT", slug: "select", description: "SELECT - Learn more about SELECT." },
      { name: "INSERT", slug: "insert", description: "INSERT - Learn more about INSERT." },
      { name: "UPDATE", slug: "update", description: "UPDATE - Learn more about UPDATE." },
      { name: "DELETE", slug: "delete", description: "DELETE - Learn more about DELETE." },
      { name: "JOINs", slug: "joins", description: "JOINs - Learn more about JOINs." },
      { name: "Aggregations", slug: "aggregations", description: "Aggregations - Learn more about Aggregations." },
      { name: "Indexes", slug: "indexes", description: "Indexes - Learn more about Indexes." },
      { name: "Constraints", slug: "constraints", description: "Constraints - Learn more about Constraints." },
      { name: "Transactions", slug: "transactions", description: "Transactions - Learn more about Transactions." },
      { name: "Normalisation", slug: "normalisation", description: "Normalisation - Learn more about Normalisation." },
      { name: "PostgreSQL", slug: "postgresql", description: "PostgreSQL - Learn more about PostgreSQL." },
      { name: "NoSQL", slug: "nosql", description: "NoSQL - Learn more about NoSQL." },
      { name: "MongoDB", slug: "mongodb", description: "MongoDB - Learn more about MongoDB." },
      { name: "Supabase", slug: "supabase", description: "Supabase - Learn more about Supabase." },
    ],
  },
  {
    id: 12,
    name: "APIs",
    slug: "apis",
    description: "Designing and consuming web APIs.",
    topics: [
      { name: "What is an API?", slug: "what-is-an-api", description: "What is an API? - Learn more about What is an API?." },
      { name: "REST APIs", slug: "rest-apis", description: "REST APIs - Learn more about REST APIs." },
      { name: "HTTP", slug: "http", description: "HTTP - Learn more about HTTP." },
      { name: "JSON", slug: "json", description: "JSON - Learn more about JSON." },
      { name: "API requests", slug: "api-requests", description: "API requests - Learn more about API requests." },
      { name: "API responses", slug: "api-responses", description: "API responses - Learn more about API responses." },
      { name: "GET", slug: "get", description: "GET - Learn more about GET." },
      { name: "POST", slug: "post", description: "POST - Learn more about POST." },
      { name: "PUT", slug: "put", description: "PUT - Learn more about PUT." },
      { name: "PATCH", slug: "patch", description: "PATCH - Learn more about PATCH." },
      { name: "DELETE", slug: "delete", description: "DELETE - Learn more about DELETE." },
      { name: "Authentication", slug: "authentication", description: "Authentication - Learn more about Authentication." },
      { name: "API keys", slug: "api-keys", description: "API keys - Learn more about API keys." },
      { name: "Pagination", slug: "pagination", description: "Pagination - Learn more about Pagination." },
      { name: "Filtering", slug: "filtering", description: "Filtering - Learn more about Filtering." },
      { name: "Error handling", slug: "error-handling", description: "Error handling - Learn more about Error handling." },
      { name: "API testing", slug: "api-testing", description: "API testing - Learn more about API testing." },
      { name: "API documentation", slug: "api-documentation", description: "API documentation - Learn more about API documentation." },
      { name: "Third-party APIs", slug: "third-party-apis", description: "Third-party APIs - Learn more about Third-party APIs." },
      { name: "Webhooks", slug: "webhooks", description: "Webhooks - Learn more about Webhooks." },
    ],
  },
  {
    id: 13,
    name: "Git & GitHub",
    slug: "git-and-github",
    description: "Version control and collaboration.",
    topics: [
      { name: "Git fundamentals", slug: "git-fundamentals", description: "Git fundamentals - Learn more about Git fundamentals." },
      { name: "Repositories", slug: "repositories", description: "Repositories - Learn more about Repositories." },
      { name: "git init", slug: "git-init", description: "git init - Learn more about git init." },
      { name: "git clone", slug: "git-clone", description: "git clone - Learn more about git clone." },
      { name: "git add", slug: "git-add", description: "git add - Learn more about git add." },
      { name: "git commit", slug: "git-commit", description: "git commit - Learn more about git commit." },
      { name: "git push", slug: "git-push", description: "git push - Learn more about git push." },
      { name: "git pull", slug: "git-pull", description: "git pull - Learn more about git pull." },
      { name: "Branches", slug: "branches", description: "Branches - Learn more about Branches." },
      { name: "Merging", slug: "merging", description: "Merging - Learn more about Merging." },
      { name: "Rebasing", slug: "rebasing", description: "Rebasing - Learn more about Rebasing." },
      { name: "Merge conflicts", slug: "merge-conflicts", description: "Merge conflicts - Learn more about Merge conflicts." },
      { name: "Pull requests", slug: "pull-requests", description: "Pull requests - Learn more about Pull requests." },
      { name: "Code reviews", slug: "code-reviews", description: "Code reviews - Learn more about Code reviews." },
      { name: "Issues", slug: "issues", description: "Issues - Learn more about Issues." },
      { name: "Tags", slug: "tags", description: "Tags - Learn more about Tags." },
      { name: "Releases", slug: "releases", description: "Releases - Learn more about Releases." },
      { name: "GitHub Actions", slug: "github-actions", description: "GitHub Actions - Learn more about GitHub Actions." },
      { name: "GitHub Projects", slug: "github-projects", description: "GitHub Projects - Learn more about GitHub Projects." },
    ],
  },
  {
    id: 14,
    name: "Software Engineering",
    slug: "software-engineering",
    description: "Professional software development practices.",
    topics: [
      { name: "SDLC", slug: "sdlc", description: "SDLC - Learn more about SDLC." },
      { name: "Requirements", slug: "requirements", description: "Requirements - Learn more about Requirements." },
      { name: "System design", slug: "system-design", description: "System design - Learn more about System design." },
      { name: "Architecture", slug: "architecture", description: "Architecture - Learn more about Architecture." },
      { name: "Design patterns", slug: "design-patterns", description: "Design patterns - Learn more about Design patterns." },
      { name: "SOLID principles", slug: "solid-principles", description: "SOLID principles - Learn more about SOLID principles." },
      { name: "Clean code", slug: "clean-code", description: "Clean code - Learn more about Clean code." },
      { name: "DRY", slug: "dry", description: "DRY - Learn more about DRY." },
      { name: "KISS", slug: "kiss", description: "KISS - Learn more about KISS." },
      { name: "Separation of concerns", slug: "separation-of-concerns", description: "Separation of concerns - Learn more about Separation of concerns." },
      { name: "Modular programming", slug: "modular-programming", description: "Modular programming - Learn more about Modular programming." },
      { name: "OOP", slug: "oop", description: "OOP - Learn more about OOP." },
      { name: "Functional programming", slug: "functional-programming", description: "Functional programming - Learn more about Functional programming." },
      { name: "Refactoring", slug: "refactoring", description: "Refactoring - Learn more about Refactoring." },
      { name: "Code reviews", slug: "code-reviews", description: "Code reviews - Learn more about Code reviews." },
      { name: "Documentation", slug: "documentation", description: "Documentation - Learn more about Documentation." },
      { name: "Version control", slug: "version-control", description: "Version control - Learn more about Version control." },
      { name: "Testing", slug: "testing", description: "Testing - Learn more about Testing." },
      { name: "CI/CD", slug: "ci-cd", description: "CI/CD - Learn more about CI/CD." },
    ],
  },
  {
    id: 15,
    name: "Object-Oriented Programming",
    slug: "object-oriented-programming",
    description: "OOP principles and patterns.",
    topics: [
      { name: "Classes", slug: "classes", description: "Classes - Learn more about Classes." },
      { name: "Objects", slug: "objects", description: "Objects - Learn more about Objects." },
      { name: "Constructors", slug: "constructors", description: "Constructors - Learn more about Constructors." },
      { name: "Methods", slug: "methods", description: "Methods - Learn more about Methods." },
      { name: "Properties", slug: "properties", description: "Properties - Learn more about Properties." },
      { name: "Encapsulation", slug: "encapsulation", description: "Encapsulation - Learn more about Encapsulation." },
      { name: "Inheritance", slug: "inheritance", description: "Inheritance - Learn more about Inheritance." },
      { name: "Polymorphism", slug: "polymorphism", description: "Polymorphism - Learn more about Polymorphism." },
      { name: "Abstraction", slug: "abstraction", description: "Abstraction - Learn more about Abstraction." },
      { name: "Interfaces", slug: "interfaces", description: "Interfaces - Learn more about Interfaces." },
      { name: "Composition", slug: "composition", description: "Composition - Learn more about Composition." },
      { name: "Dependency injection", slug: "dependency-injection", description: "Dependency injection - Learn more about Dependency injection." },
      { name: "SOLID principles", slug: "solid-principles", description: "SOLID principles - Learn more about SOLID principles." },
    ],
  },
  {
    id: 16,
    name: "Testing",
    slug: "testing",
    description: "Software testing fundamentals.",
    topics: [
      { name: "Testing fundamentals", slug: "testing-fundamentals", description: "Testing fundamentals - Learn more about Testing fundamentals." },
      { name: "Unit testing", slug: "unit-testing", description: "Unit testing - Learn more about Unit testing." },
      { name: "Integration testing", slug: "integration-testing", description: "Integration testing - Learn more about Integration testing." },
      { name: "E2E testing", slug: "e2e-testing", description: "E2E testing - Learn more about E2E testing." },
      { name: "TDD", slug: "tdd", description: "TDD - Learn more about TDD." },
      { name: "Test cases", slug: "test-cases", description: "Test cases - Learn more about Test cases." },
      { name: "Assertions", slug: "assertions", description: "Assertions - Learn more about Assertions." },
      { name: "Mocking", slug: "mocking", description: "Mocking - Learn more about Mocking." },
      { name: "Test coverage", slug: "test-coverage", description: "Test coverage - Learn more about Test coverage." },
      { name: "Jest", slug: "jest", description: "Jest - Learn more about Jest." },
      { name: "React Testing Library", slug: "react-testing-library", description: "React Testing Library - Learn more about React Testing Library." },
      { name: "API testing", slug: "api-testing", description: "API testing - Learn more about API testing." },
      { name: "Debugging", slug: "debugging", description: "Debugging - Learn more about Debugging." },
    ],
  },
  {
    id: 17,
    name: "Python",
    slug: "python",
    description: "A versatile programming language.",
    topics: [
      { name: "Python fundamentals", slug: "python-fundamentals", description: "Python fundamentals - Learn more about Python fundamentals." },
      { name: "Variables", slug: "variables", description: "Variables - Learn more about Variables." },
      { name: "Data types", slug: "data-types", description: "Data types - Learn more about Data types." },
      { name: "Conditions", slug: "conditions", description: "Conditions - Learn more about Conditions." },
      { name: "Loops", slug: "loops", description: "Loops - Learn more about Loops." },
      { name: "Functions", slug: "functions", description: "Functions - Learn more about Functions." },
      { name: "Lists", slug: "lists", description: "Lists - Learn more about Lists." },
      { name: "Tuples", slug: "tuples", description: "Tuples - Learn more about Tuples." },
      { name: "Dictionaries", slug: "dictionaries", description: "Dictionaries - Learn more about Dictionaries." },
      { name: "Sets", slug: "sets", description: "Sets - Learn more about Sets." },
      { name: "Modules", slug: "modules", description: "Modules - Learn more about Modules." },
      { name: "Packages", slug: "packages", description: "Packages - Learn more about Packages." },
      { name: "File handling", slug: "file-handling", description: "File handling - Learn more about File handling." },
      { name: "Exceptions", slug: "exceptions", description: "Exceptions - Learn more about Exceptions." },
      { name: "OOP", slug: "oop", description: "OOP - Learn more about OOP." },
      { name: "Virtual environments", slug: "virtual-environments", description: "Virtual environments - Learn more about Virtual environments." },
      { name: "APIs", slug: "apis", description: "APIs - Learn more about APIs." },
      { name: "Automation", slug: "automation", description: "Automation - Learn more about Automation." },
    ],
  },
  {
    id: 18,
    name: "C++",
    slug: "cpp",
    description: "A powerful systems programming language.",
    topics: [
      { name: "C++ fundamentals", slug: "c-fundamentals", description: "C++ fundamentals - Learn more about C++ fundamentals." },
      { name: "Variables", slug: "variables", description: "Variables - Learn more about Variables." },
      { name: "Data types", slug: "data-types", description: "Data types - Learn more about Data types." },
      { name: "Operators", slug: "operators", description: "Operators - Learn more about Operators." },
      { name: "Conditions", slug: "conditions", description: "Conditions - Learn more about Conditions." },
      { name: "Loops", slug: "loops", description: "Loops - Learn more about Loops." },
      { name: "Functions", slug: "functions", description: "Functions - Learn more about Functions." },
      { name: "Arrays", slug: "arrays", description: "Arrays - Learn more about Arrays." },
      { name: "Strings", slug: "strings", description: "Strings - Learn more about Strings." },
      { name: "Pointers", slug: "pointers", description: "Pointers - Learn more about Pointers." },
      { name: "References", slug: "references", description: "References - Learn more about References." },
      { name: "Memory", slug: "memory", description: "Memory - Learn more about Memory." },
      { name: "Structs", slug: "structs", description: "Structs - Learn more about Structs." },
      { name: "Classes", slug: "classes", description: "Classes - Learn more about Classes." },
      { name: "OOP", slug: "oop", description: "OOP - Learn more about OOP." },
      { name: "Inheritance", slug: "inheritance", description: "Inheritance - Learn more about Inheritance." },
      { name: "Polymorphism", slug: "polymorphism", description: "Polymorphism - Learn more about Polymorphism." },
      { name: "Templates", slug: "templates", description: "Templates - Learn more about Templates." },
      { name: "STL", slug: "stl", description: "STL - Learn more about STL." },
      { name: "Vectors", slug: "vectors", description: "Vectors - Learn more about Vectors." },
      { name: "Maps", slug: "maps", description: "Maps - Learn more about Maps." },
      { name: "Sets", slug: "sets", description: "Sets - Learn more about Sets." },
      { name: "Algorithms", slug: "algorithms", description: "Algorithms - Learn more about Algorithms." },
      { name: "File handling", slug: "file-handling", description: "File handling - Learn more about File handling." },
      { name: "Exception handling", slug: "exception-handling", description: "Exception handling - Learn more about Exception handling." },
    ],
  },
  {
    id: 19,
    name: "Java",
    slug: "java",
    description: "A widely-used OOP language.",
    topics: [
      { name: "Java fundamentals", slug: "java-fundamentals", description: "Java fundamentals - Learn more about Java fundamentals." },
      { name: "Variables", slug: "variables", description: "Variables - Learn more about Variables." },
      { name: "Data types", slug: "data-types", description: "Data types - Learn more about Data types." },
      { name: "Conditions", slug: "conditions", description: "Conditions - Learn more about Conditions." },
      { name: "Loops", slug: "loops", description: "Loops - Learn more about Loops." },
      { name: "Methods", slug: "methods", description: "Methods - Learn more about Methods." },
      { name: "Arrays", slug: "arrays", description: "Arrays - Learn more about Arrays." },
      { name: "Classes", slug: "classes", description: "Classes - Learn more about Classes." },
      { name: "Objects", slug: "objects", description: "Objects - Learn more about Objects." },
      { name: "OOP", slug: "oop", description: "OOP - Learn more about OOP." },
      { name: "Interfaces", slug: "interfaces", description: "Interfaces - Learn more about Interfaces." },
      { name: "Inheritance", slug: "inheritance", description: "Inheritance - Learn more about Inheritance." },
      { name: "Exceptions", slug: "exceptions", description: "Exceptions - Learn more about Exceptions." },
      { name: "Collections", slug: "collections", description: "Collections - Learn more about Collections." },
      { name: "Generics", slug: "generics", description: "Generics - Learn more about Generics." },
      { name: "Streams", slug: "streams", description: "Streams - Learn more about Streams." },
      { name: "Multithreading", slug: "multithreading", description: "Multithreading - Learn more about Multithreading." },
      { name: "Spring Boot", slug: "spring-boot", description: "Spring Boot - Learn more about Spring Boot." },
    ],
  },
  {
    id: 20,
    name: "SQL",
    slug: "sql",
    description: "Standard language for relational databases.",
    topics: [
      { name: "SQL fundamentals", slug: "sql-fundamentals", description: "SQL fundamentals - Learn more about SQL fundamentals." },
      { name: "SELECT", slug: "select", description: "SELECT - Learn more about SELECT." },
      { name: "INSERT", slug: "insert", description: "INSERT - Learn more about INSERT." },
      { name: "UPDATE", slug: "update", description: "UPDATE - Learn more about UPDATE." },
      { name: "DELETE", slug: "delete", description: "DELETE - Learn more about DELETE." },
      { name: "WHERE", slug: "where", description: "WHERE - Learn more about WHERE." },
      { name: "ORDER BY", slug: "order-by", description: "ORDER BY - Learn more about ORDER BY." },
      { name: "GROUP BY", slug: "group-by", description: "GROUP BY - Learn more about GROUP BY." },
      { name: "HAVING", slug: "having", description: "HAVING - Learn more about HAVING." },
      { name: "JOINs", slug: "joins", description: "JOINs - Learn more about JOINs." },
      { name: "Subqueries", slug: "subqueries", description: "Subqueries - Learn more about Subqueries." },
      { name: "Aggregate functions", slug: "aggregate-functions", description: "Aggregate functions - Learn more about Aggregate functions." },
      { name: "Views", slug: "views", description: "Views - Learn more about Views." },
      { name: "Indexes", slug: "indexes", description: "Indexes - Learn more about Indexes." },
      { name: "Constraints", slug: "constraints", description: "Constraints - Learn more about Constraints." },
      { name: "Transactions", slug: "transactions", description: "Transactions - Learn more about Transactions." },
      { name: "Stored procedures", slug: "stored-procedures", description: "Stored procedures - Learn more about Stored procedures." },
      { name: "Database optimisation", slug: "database-optimisation", description: "Database optimisation - Learn more about Database optimisation." },
    ],
  },
  {
    id: 21,
    name: "Data Science",
    slug: "data-science",
    description: "Data analysis and machine learning.",
    topics: [
      { name: "Python for data science", slug: "python-for-data-science", description: "Python for data science - Learn more about Python for data science." },
      { name: "NumPy", slug: "numpy", description: "NumPy - Learn more about NumPy." },
      { name: "Pandas", slug: "pandas", description: "Pandas - Learn more about Pandas." },
      { name: "Data cleaning", slug: "data-cleaning", description: "Data cleaning - Learn more about Data cleaning." },
      { name: "Data preprocessing", slug: "data-preprocessing", description: "Data preprocessing - Learn more about Data preprocessing." },
      { name: "EDA", slug: "eda", description: "EDA - Learn more about EDA." },
      { name: "Statistics", slug: "statistics", description: "Statistics - Learn more about Statistics." },
      { name: "Probability", slug: "probability", description: "Probability - Learn more about Probability." },
      { name: "Data visualisation", slug: "data-visualisation", description: "Data visualisation - Learn more about Data visualisation." },
      { name: "Matplotlib", slug: "matplotlib", description: "Matplotlib - Learn more about Matplotlib." },
      { name: "ML fundamentals", slug: "ml-fundamentals", description: "ML fundamentals - Learn more about ML fundamentals." },
      { name: "Scikit-learn", slug: "scikit-learn", description: "Scikit-learn - Learn more about Scikit-learn." },
      { name: "Regression", slug: "regression", description: "Regression - Learn more about Regression." },
      { name: "Classification", slug: "classification", description: "Classification - Learn more about Classification." },
      { name: "Clustering", slug: "clustering", description: "Clustering - Learn more about Clustering." },
      { name: "Model evaluation", slug: "model-evaluation", description: "Model evaluation - Learn more about Model evaluation." },
    ],
  },
  {
    id: 22,
    name: "Artificial Intelligence",
    slug: "artificial-intelligence",
    description: "AI and machine learning concepts.",
    topics: [
      { name: "AI fundamentals", slug: "ai-fundamentals", description: "AI fundamentals - Learn more about AI fundamentals." },
      { name: "Machine learning", slug: "machine-learning", description: "Machine learning - Learn more about Machine learning." },
      { name: "Supervised learning", slug: "supervised-learning", description: "Supervised learning - Learn more about Supervised learning." },
      { name: "Unsupervised learning", slug: "unsupervised-learning", description: "Unsupervised learning - Learn more about Unsupervised learning." },
      { name: "Reinforcement learning", slug: "reinforcement-learning", description: "Reinforcement learning - Learn more about Reinforcement learning." },
      { name: "Neural networks", slug: "neural-networks", description: "Neural networks - Learn more about Neural networks." },
      { name: "Deep learning", slug: "deep-learning", description: "Deep learning - Learn more about Deep learning." },
      { name: "TensorFlow", slug: "tensorflow", description: "TensorFlow - Learn more about TensorFlow." },
      { name: "Keras", slug: "keras", description: "Keras - Learn more about Keras." },
      { name: "Computer vision", slug: "computer-vision", description: "Computer vision - Learn more about Computer vision." },
      { name: "NLP", slug: "nlp", description: "NLP - Learn more about NLP." },
      { name: "Generative AI", slug: "generative-ai", description: "Generative AI - Learn more about Generative AI." },
      { name: "LLMs", slug: "llms", description: "LLMs - Learn more about LLMs." },
      { name: "Prompt engineering", slug: "prompt-engineering", description: "Prompt engineering - Learn more about Prompt engineering." },
      { name: "AI APIs", slug: "ai-apis", description: "AI APIs - Learn more about AI APIs." },
      { name: "AI app development", slug: "ai-app-development", description: "AI app development - Learn more about AI app development." },
    ],
  },
  {
    id: 23,
    name: "Cybersecurity",
    slug: "cybersecurity",
    description: "Security fundamentals and secure coding.",
    topics: [
      { name: "Security fundamentals", slug: "security-fundamentals", description: "Security fundamentals - Learn more about Security fundamentals." },
      { name: "Networking basics", slug: "networking-basics", description: "Networking basics - Learn more about Networking basics." },
      { name: "Authentication", slug: "authentication", description: "Authentication - Learn more about Authentication." },
      { name: "Authorisation", slug: "authorisation", description: "Authorisation - Learn more about Authorisation." },
      { name: "Encryption", slug: "encryption", description: "Encryption - Learn more about Encryption." },
      { name: "Hashing", slug: "hashing", description: "Hashing - Learn more about Hashing." },
      { name: "Password security", slug: "password-security", description: "Password security - Learn more about Password security." },
      { name: "Web security", slug: "web-security", description: "Web security - Learn more about Web security." },
      { name: "OWASP", slug: "owasp", description: "OWASP - Learn more about OWASP." },
      { name: "Secure coding", slug: "secure-coding", description: "Secure coding - Learn more about Secure coding." },
      { name: "SQL injection", slug: "sql-injection", description: "SQL injection - Learn more about SQL injection." },
      { name: "XSS", slug: "xss", description: "XSS - Learn more about XSS." },
      { name: "CSRF", slug: "csrf", description: "CSRF - Learn more about CSRF." },
      { name: "API security", slug: "api-security", description: "API security - Learn more about API security." },
      { name: "Security testing", slug: "security-testing", description: "Security testing - Learn more about Security testing." },
      { name: "Threat modelling", slug: "threat-modelling", description: "Threat modelling - Learn more about Threat modelling." },
      { name: "Privacy", slug: "privacy", description: "Privacy - Learn more about Privacy." },
    ],
  },
  {
    id: 24,
    name: "Networking",
    slug: "networking",
    description: "Computer networking fundamentals.",
    topics: [
      { name: "Networking fundamentals", slug: "networking-fundamentals", description: "Networking fundamentals - Learn more about Networking fundamentals." },
      { name: "IP addresses", slug: "ip-addresses", description: "IP addresses - Learn more about IP addresses." },
      { name: "IPv4", slug: "ipv4", description: "IPv4 - Learn more about IPv4." },
      { name: "IPv6", slug: "ipv6", description: "IPv6 - Learn more about IPv6." },
      { name: "DNS", slug: "dns", description: "DNS - Learn more about DNS." },
      { name: "DHCP", slug: "dhcp", description: "DHCP - Learn more about DHCP." },
      { name: "HTTP", slug: "http", description: "HTTP - Learn more about HTTP." },
      { name: "HTTPS", slug: "https", description: "HTTPS - Learn more about HTTPS." },
      { name: "TCP", slug: "tcp", description: "TCP - Learn more about TCP." },
      { name: "UDP", slug: "udp", description: "UDP - Learn more about UDP." },
      { name: "Ports", slug: "ports", description: "Ports - Learn more about Ports." },
      { name: "Firewalls", slug: "firewalls", description: "Firewalls - Learn more about Firewalls." },
      { name: "Routers", slug: "routers", description: "Routers - Learn more about Routers." },
      { name: "Switches", slug: "switches", description: "Switches - Learn more about Switches." },
      { name: "Subnets", slug: "subnets", description: "Subnets - Learn more about Subnets." },
      { name: "VPNs", slug: "vpns", description: "VPNs - Learn more about VPNs." },
      { name: "Network security", slug: "network-security", description: "Network security - Learn more about Network security." },
    ],
  },
  {
    id: 25,
    name: "Cloud Computing",
    slug: "cloud-computing",
    description: "Cloud platforms and services.",
    topics: [
      { name: "Cloud fundamentals", slug: "cloud-fundamentals", description: "Cloud fundamentals - Learn more about Cloud fundamentals." },
      { name: "AWS", slug: "aws", description: "AWS - Learn more about AWS." },
      { name: "Azure", slug: "azure", description: "Azure - Learn more about Azure." },
      { name: "Google Cloud", slug: "google-cloud", description: "Google Cloud - Learn more about Google Cloud." },
      { name: "Virtual machines", slug: "virtual-machines", description: "Virtual machines - Learn more about Virtual machines." },
      { name: "Storage", slug: "storage", description: "Storage - Learn more about Storage." },
      { name: "Databases", slug: "databases", description: "Databases - Learn more about Databases." },
      { name: "Serverless", slug: "serverless", description: "Serverless - Learn more about Serverless." },
      { name: "Containers", slug: "containers", description: "Containers - Learn more about Containers." },
      { name: "Cloud networking", slug: "cloud-networking", description: "Cloud networking - Learn more about Cloud networking." },
      { name: "IAM", slug: "iam", description: "IAM - Learn more about IAM." },
      { name: "Monitoring", slug: "monitoring", description: "Monitoring - Learn more about Monitoring." },
      { name: "Scaling", slug: "scaling", description: "Scaling - Learn more about Scaling." },
      { name: "Cloud security", slug: "cloud-security", description: "Cloud security - Learn more about Cloud security." },
    ],
  },
  {
    id: 26,
    name: "DevOps",
    slug: "devops",
    description: "DevOps practices and tools.",
    topics: [
      { name: "DevOps fundamentals", slug: "devops-fundamentals", description: "DevOps fundamentals - Learn more about DevOps fundamentals." },
      { name: "CI/CD", slug: "ci-cd", description: "CI/CD - Learn more about CI/CD." },
      { name: "Docker", slug: "docker", description: "Docker - Learn more about Docker." },
      { name: "Containers", slug: "containers", description: "Containers - Learn more about Containers." },
      { name: "Kubernetes", slug: "kubernetes", description: "Kubernetes - Learn more about Kubernetes." },
      { name: "GitHub Actions", slug: "github-actions", description: "GitHub Actions - Learn more about GitHub Actions." },
      { name: "Jenkins", slug: "jenkins", description: "Jenkins - Learn more about Jenkins." },
      { name: "IaC", slug: "iac", description: "IaC - Learn more about IaC." },
      { name: "Monitoring", slug: "monitoring", description: "Monitoring - Learn more about Monitoring." },
      { name: "Logging", slug: "logging", description: "Logging - Learn more about Logging." },
      { name: "Deployment", slug: "deployment", description: "Deployment - Learn more about Deployment." },
      { name: "Cloud deployment", slug: "cloud-deployment", description: "Cloud deployment - Learn more about Cloud deployment." },
      { name: "Automation", slug: "automation", description: "Automation - Learn more about Automation." },
    ],
  },
  {
    id: 27,
    name: "Linux",
    slug: "linux",
    description: "Linux fundamentals and command line.",
    topics: [
      { name: "Linux fundamentals", slug: "linux-fundamentals", description: "Linux fundamentals - Learn more about Linux fundamentals." },
      { name: "Terminal", slug: "terminal", description: "Terminal - Learn more about Terminal." },
      { name: "File system", slug: "file-system", description: "File system - Learn more about File system." },
      { name: "Permissions", slug: "permissions", description: "Permissions - Learn more about Permissions." },
      { name: "Users", slug: "users", description: "Users - Learn more about Users." },
      { name: "Processes", slug: "processes", description: "Processes - Learn more about Processes." },
      { name: "Packages", slug: "packages", description: "Packages - Learn more about Packages." },
      { name: "Shell commands", slug: "shell-commands", description: "Shell commands - Learn more about Shell commands." },
      { name: "Bash", slug: "bash", description: "Bash - Learn more about Bash." },
      { name: "Environment variables", slug: "environment-variables", description: "Environment variables - Learn more about Environment variables." },
      { name: "SSH", slug: "ssh", description: "SSH - Learn more about SSH." },
      { name: "Networking", slug: "networking", description: "Networking - Learn more about Networking." },
      { name: "Shell scripting", slug: "shell-scripting", description: "Shell scripting - Learn more about Shell scripting." },
      { name: "Server management", slug: "server-management", description: "Server management - Learn more about Server management." },
    ],
  },
  {
    id: 28,
    name: "Mobile Development",
    slug: "mobile-development",
    description: "Building mobile applications.",
    topics: [
      { name: "Mobile fundamentals", slug: "mobile-fundamentals", description: "Mobile fundamentals - Learn more about Mobile fundamentals." },
      { name: "React Native", slug: "react-native", description: "React Native - Learn more about React Native." },
      { name: "Android development", slug: "android-development", description: "Android development - Learn more about Android development." },
      { name: "iOS development", slug: "ios-development", description: "iOS development - Learn more about iOS development." },
      { name: "Navigation", slug: "navigation", description: "Navigation - Learn more about Navigation." },
      { name: "Mobile UI", slug: "mobile-ui", description: "Mobile UI - Learn more about Mobile UI." },
      { name: "APIs", slug: "apis", description: "APIs - Learn more about APIs." },
      { name: "Authentication", slug: "authentication", description: "Authentication - Learn more about Authentication." },
      { name: "Local storage", slug: "local-storage", description: "Local storage - Learn more about Local storage." },
      { name: "Notifications", slug: "notifications", description: "Notifications - Learn more about Notifications." },
      { name: "App deployment", slug: "app-deployment", description: "App deployment - Learn more about App deployment." },
    ],
  },
  {
    id: 29,
    name: "Game Development",
    slug: "game-development",
    description: "Game programming and design.",
    topics: [
      { name: "Game programming", slug: "game-programming", description: "Game programming - Learn more about Game programming." },
      { name: "Game loops", slug: "game-loops", description: "Game loops - Learn more about Game loops." },
      { name: "Physics", slug: "physics", description: "Physics - Learn more about Physics." },
      { name: "Collision detection", slug: "collision-detection", description: "Collision detection - Learn more about Collision detection." },
      { name: "Animation", slug: "animation", description: "Animation - Learn more about Animation." },
      { name: "Game states", slug: "game-states", description: "Game states - Learn more about Game states." },
      { name: "Input handling", slug: "input-handling", description: "Input handling - Learn more about Input handling." },
      { name: "2D games", slug: "2d-games", description: "2D games - Learn more about 2D games." },
      { name: "3D concepts", slug: "3d-concepts", description: "3D concepts - Learn more about 3D concepts." },
      { name: "Unity", slug: "unity", description: "Unity - Learn more about Unity." },
      { name: "Unreal Engine", slug: "unreal-engine", description: "Unreal Engine - Learn more about Unreal Engine." },
    ],
  },
  {
    id: 30,
    name: "Blockchain & Web3",
    slug: "blockchain-and-web3",
    description: "Blockchain fundamentals and dApps.",
    topics: [
      { name: "Blockchain fundamentals", slug: "blockchain-fundamentals", description: "Blockchain fundamentals - Learn more about Blockchain fundamentals." },
      { name: "Cryptography", slug: "cryptography", description: "Cryptography - Learn more about Cryptography." },
      { name: "Wallets", slug: "wallets", description: "Wallets - Learn more about Wallets." },
      { name: "Transactions", slug: "transactions", description: "Transactions - Learn more about Transactions." },
      { name: "Smart contracts", slug: "smart-contracts", description: "Smart contracts - Learn more about Smart contracts." },
      { name: "Solidity", slug: "solidity", description: "Solidity - Learn more about Solidity." },
      { name: "Ethereum", slug: "ethereum", description: "Ethereum - Learn more about Ethereum." },
      { name: "Web3 APIs", slug: "web3-apis", description: "Web3 APIs - Learn more about Web3 APIs." },
      { name: "Decentralised applications", slug: "decentralised-applications", description: "Decentralised applications - Learn more about Decentralised applications." },
      { name: "Blockchain security", slug: "blockchain-security", description: "Blockchain security - Learn more about Blockchain security." },
    ],
  },
  {
    id: 31,
    name: "Web Performance",
    slug: "web-performance",
    description: "Optimising web performance.",
    topics: [
      { name: "Page speed", slug: "page-speed", description: "Page speed - Learn more about Page speed." },
      { name: "Image optimisation", slug: "image-optimisation", description: "Image optimisation - Learn more about Image optimisation." },
      { name: "Lazy loading", slug: "lazy-loading", description: "Lazy loading - Learn more about Lazy loading." },
      { name: "Code splitting", slug: "code-splitting", description: "Code splitting - Learn more about Code splitting." },
      { name: "Caching", slug: "caching", description: "Caching - Learn more about Caching." },
      { name: "Browser performance", slug: "browser-performance", description: "Browser performance - Learn more about Browser performance." },
      { name: "Network optimisation", slug: "network-optimisation", description: "Network optimisation - Learn more about Network optimisation." },
      { name: "Bundle optimisation", slug: "bundle-optimisation", description: "Bundle optimisation - Learn more about Bundle optimisation." },
      { name: "Core Web Vitals", slug: "core-web-vitals", description: "Core Web Vitals - Learn more about Core Web Vitals." },
    ],
  },
  {
    id: 32,
    name: "Web Accessibility",
    slug: "web-accessibility",
    description: "Making web content accessible.",
    topics: [
      { name: "WCAG concepts", slug: "wcag-concepts", description: "WCAG concepts - Learn more about WCAG concepts." },
      { name: "Semantic HTML", slug: "semantic-html", description: "Semantic HTML - Learn more about Semantic HTML." },
      { name: "Keyboard navigation", slug: "keyboard-navigation", description: "Keyboard navigation - Learn more about Keyboard navigation." },
      { name: "Screen readers", slug: "screen-readers", description: "Screen readers - Learn more about Screen readers." },
      { name: "ARIA", slug: "aria", description: "ARIA - Learn more about ARIA." },
      { name: "Colour contrast", slug: "colour-contrast", description: "Colour contrast - Learn more about Colour contrast." },
      { name: "Accessible forms", slug: "accessible-forms", description: "Accessible forms - Learn more about Accessible forms." },
      { name: "Accessible navigation", slug: "accessible-navigation", description: "Accessible navigation - Learn more about Accessible navigation." },
    ],
  },
  {
    id: 33,
    name: "Software Architecture",
    slug: "software-architecture",
    description: "Application architecture patterns.",
    topics: [
      { name: "Monolithic applications", slug: "monolithic-applications", description: "Monolithic applications - Learn more about Monolithic applications." },
      { name: "Modular architecture", slug: "modular-architecture", description: "Modular architecture - Learn more about Modular architecture." },
      { name: "Microservices", slug: "microservices", description: "Microservices - Learn more about Microservices." },
      { name: "Event-driven architecture", slug: "event-driven-architecture", description: "Event-driven architecture - Learn more about Event-driven architecture." },
      { name: "Layered architecture", slug: "layered-architecture", description: "Layered architecture - Learn more about Layered architecture." },
      { name: "MVC", slug: "mvc", description: "MVC - Learn more about MVC." },
      { name: "REST architecture", slug: "rest-architecture", description: "REST architecture - Learn more about REST architecture." },
      { name: "Scalability", slug: "scalability", description: "Scalability - Learn more about Scalability." },
      { name: "Caching", slug: "caching", description: "Caching - Learn more about Caching." },
      { name: "Load balancing", slug: "load-balancing", description: "Load balancing - Learn more about Load balancing." },
      { name: "Distributed systems", slug: "distributed-systems", description: "Distributed systems - Learn more about Distributed systems." },
    ],
  },
  {
    id: 34,
    name: "System Design",
    slug: "system-design",
    description: "Designing scalable systems.",
    topics: [
      { name: "Requirements", slug: "requirements", description: "Requirements - Learn more about Requirements." },
      { name: "Architecture diagrams", slug: "architecture-diagrams", description: "Architecture diagrams - Learn more about Architecture diagrams." },
      { name: "Scalability", slug: "scalability", description: "Scalability - Learn more about Scalability." },
      { name: "Availability", slug: "availability", description: "Availability - Learn more about Availability." },
      { name: "Reliability", slug: "reliability", description: "Reliability - Learn more about Reliability." },
      { name: "Databases", slug: "databases", description: "Databases - Learn more about Databases." },
      { name: "Caching", slug: "caching", description: "Caching - Learn more about Caching." },
      { name: "Queues", slug: "queues", description: "Queues - Learn more about Queues." },
      { name: "Load balancing", slug: "load-balancing", description: "Load balancing - Learn more about Load balancing." },
      { name: "APIs", slug: "apis", description: "APIs - Learn more about APIs." },
      { name: "Distributed systems", slug: "distributed-systems", description: "Distributed systems - Learn more about Distributed systems." },
      { name: "CAP concepts", slug: "cap-concepts", description: "CAP concepts - Learn more about CAP concepts." },
    ],
  },
  {
    id: 35,
    name: "Interview Preparation",
    slug: "interview-preparation",
    description: "Preparing for coding interviews.",
    topics: [
      { name: "Coding interviews", slug: "coding-interviews", description: "Coding interviews - Learn more about Coding interviews." },
      { name: "Algorithms", slug: "algorithms", description: "Algorithms - Learn more about Algorithms." },
      { name: "Data structures", slug: "data-structures", description: "Data structures - Learn more about Data structures." },
      { name: "JS interviews", slug: "js-interviews", description: "JS interviews - Learn more about JS interviews." },
      { name: "TS interviews", slug: "ts-interviews", description: "TS interviews - Learn more about TS interviews." },
      { name: "React interviews", slug: "react-interviews", description: "React interviews - Learn more about React interviews." },
      { name: "Backend interviews", slug: "backend-interviews", description: "Backend interviews - Learn more about Backend interviews." },
      { name: "SQL interviews", slug: "sql-interviews", description: "SQL interviews - Learn more about SQL interviews." },
      { name: "System design", slug: "system-design", description: "System design - Learn more about System design." },
      { name: "Behavioural interviews", slug: "behavioural-interviews", description: "Behavioural interviews - Learn more about Behavioural interviews." },
      { name: "Problem-solving", slug: "problem-solving", description: "Problem-solving - Learn more about Problem-solving." },
      { name: "Mock interviews", slug: "mock-interviews", description: "Mock interviews - Learn more about Mock interviews." },
    ],
  },
  {
    id: 36,
    name: "Career Development",
    slug: "career-development",
    description: "Building a developer career.",
    topics: [
      { name: "Developer CVs", slug: "developer-cvs", description: "Developer CVs - Learn more about Developer CVs." },
      { name: "Portfolios", slug: "portfolios", description: "Portfolios - Learn more about Portfolios." },
      { name: "GitHub profiles", slug: "github-profiles", description: "GitHub profiles - Learn more about GitHub profiles." },
      { name: "LinkedIn profiles", slug: "linkedin-profiles", description: "LinkedIn profiles - Learn more about LinkedIn profiles." },
      { name: "Personal branding", slug: "personal-branding", description: "Personal branding - Learn more about Personal branding." },
      { name: "Freelancing", slug: "freelancing", description: "Freelancing - Learn more about Freelancing." },
      { name: "Software engineering careers", slug: "software-engineering-careers", description: "Software engineering careers - Learn more about Software engineering careers." },
      { name: "Junior developer preparation", slug: "junior-developer-preparation", description: "Junior developer preparation - Learn more about Junior developer preparation." },
      { name: "Technical interviews", slug: "technical-interviews", description: "Technical interviews - Learn more about Technical interviews." },
      { name: "Job readiness", slug: "job-readiness", description: "Job readiness - Learn more about Job readiness." },
    ],
  },
];

export default curriculumCategories;
